name: plaenv
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - alsa-lib=1.2.8
  - aom=3.5.0
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=24.2.0
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.9.24
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - comm=0.2.2
  - contourpy=1.2.1
  - cudatoolkit=11.3.1
  - cycler=0.12.1
  - cytoolz=0.12.2
  - dask-core=2024.8.2
  - dbus=1.13.18
  - debugpy=1.8.5
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.2
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.6.1
  - geos=3.12.2
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.38
  - h2=4.1.0
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=70.1
  - idna=3.7
  - imagecodecs-lite=2019.12.3
  - imageio=2.33.1
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jack=1.9.22
  - jasper=2.0.33
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=8.1.2
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.122
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libglu=9.0.0
  - libgomp=14.1.0
  - libgpg-error=1.50
  - libhwloc=2.9.1
  - libiconv=1.17
  - libidn2=2.3.7
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.4.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lightning-utilities=0.9.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mpg123=1.32.6
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql=5.7.20
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.3
  - nspr=4.35
  - nss=3.100
  - numpy=1.26.4
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.6
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - partd=1.4.1
  - patsy=0.5.6
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.2
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.3
  - py-opencv=4.7.0
  - pycparser=2.22
  - pyg=2.5.2
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.0
  - pytz=2024.1
  - pywavelets=1.7.0
  - pyyaml=6.0.1
  - pyzmq=26.2.0
  - qt-main=5.15.8
  - readline=8.2
  - requests=2.32.3
  - scikit-image=0.20.0
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=70.1.1
  - shapely=2.0.4
  - sip=6.5.1
  - six=1.16.0
  - sqlite=3.46.0
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - svt-av1=1.4.1
  - tbb=2021.9.0
  - threadpoolctl=3.5.0
  - tifffile=2020.6.3
  - tk=8.6.13
  - toml=0.10.2
  - toolz=0.12.0
  - torchaudio=0.12.1
  - torchmetrics=1.4.0.post0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.11.0
  - zeromq=4.3.5
  - zipp=3.20.1
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.6
  - pip:
      - antlr4-python3-runtime==4.9.3
      - anywidget==0.9.13
      - defusedxml==0.7.1
      - filelock==3.16.1
      - hydra-core==1.3.2
      - iopath==0.1.10
      - ipywidgets==8.1.5
      - jupyter-bbox-widget==0.6.0
      - jupyterlab-widgets==3.0.13
      - mpmath==1.3.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - portalocker==2.10.1
      - psygnal==0.11.1
      - sam-2==1.0
      - segment-anything==1.0
      - supervision==0.25.0
      - sympy==1.13.1
      - torch==2.5.0
      - torchvision==0.20.0
      - triton==3.1.0
      - widgetsnbextension==4.0.13
